trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

variables:
  buildConfiguration: 'Release'

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UseDotNet@2
    displayName: 'Install .NET SDK 9.x'
    inputs:
      packageType: 'sdk'
      version: '9.x'

  - script: dotnet restore
    displayName: 'Restore NuGet packages'

  - script: dotnet build --configuration $(buildConfiguration) --no-restore
    displayName: 'Build project'

  - script: dotnet test --configuration $(buildConfiguration) --no-build --verbosity normal
    displayName: 'Run unit tests'

  # Publish test results to Azure DevOps
  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/TestResults/*.xml'
      failTaskOnFailedTests: true
