// <auto-generated />
using System;
using Fonbec.Web.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fonbec.Web.DataAccess.Migrations
{
    [DbContext(typeof(FonbecWebDbContext))]
    [Migration("20260624174309_AddDocuments")]
    partial class AddDocuments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Fonbec.Web.DataAccess.Entities.Assessment", b =>
                {
                    b.Property<long>("AssessmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AssessmentId"));

                    b.Property<string>("Appraisal")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<int>("ContentScore")
                        .HasColumnType("int");

                    b.Property<bool>("HasGreenFlags")
                        .HasColumnType("bit");

                    b.Property<bool>("HasRedFlags")
                        .HasColumnType("bit");

                    b.Property<string>("IssuesNotes")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<int>("PenmanshipScore")
                        .HasColumnType("int");

                    b.Property<int>("SpellingScore")
                        .HasColumnType("int");

                    b.HasKey("AssessmentId");

                    b.ToTable("Assessments");
                });

            modelBuilder.Entity("Fonbec.Web.DataAccess.Entities.BlobPath", b =>
                {
                    b.Property<long>("BlobPathId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("BlobPathId"));

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<byte[]>("Sha256")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("BlobPathId");

                    b.ToTable("BlobPaths");
                });

            modelBuilder.Entity("Fonbec.Web.DataAccess.Entities.Chapter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DisabledById")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DisabledOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("LastUpdatedById")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastUpdatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Notes")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int?>("ReenabledById")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReenabledOnUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("DisabledById");

                    b.HasIndex("LastUpdatedById");

                    b.HasIndex("ReenabledById");

                    b.ToTable("Chapters");
                });

            modelBuilder.Entity("Fonbec.Web.DataAccess.Entities.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DisabledById")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DisabledOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("LastUpdatedById")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastUpdatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Notes")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("ReenabledById")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReenabledOnUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("DisabledById");

                    b.HasIndex("LastUpdatedById");

                    b.HasIndex("ReenabledById");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("Fonbec.Web.DataAccess.Entities.Document", b =>
                {
                    b.Property<long>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("DocumentId"));

                    b.Property<DateTime?>("ApprovedOn")
                        .HasColumnType("datetime2");

                    b.Property<long?>("BlobPathId")
                        .HasColumnType("bigint");

                    b.Property<int>("ChapterId")
                        .HasColumnType("int");

                    b.Property<byte>("DigitalImprovementStatus")
                        .HasColumnType("tinyint");

                    b.Property<byte>("DocumentType")
                        .HasColumnType("tinyint");

                    b.Property<byte>("FileKind")
                        .HasColumnType("tinyint");

                    b.Property<long?>("ImprovedBlobPathId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ImprovementLockedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ImprovementLockedById")
                        .HasColumnType("int");

                    b.Property<long?>("OriginalBlobPathId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("RejectedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RejectedReasonId")
                        .HasColumnType("int");

                    b.Property<string>("RejectionNotes")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int?>("SponsorId")
                        .HasColumnType("int");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<string>("TextContent")
                        .HasMaxLength(8192)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UploadedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("UploaderNotes")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("YouTubeVideoId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("DocumentId");

                    b.HasIndex("BlobPathId");

                    b.HasIndex("ChapterId");

                    b.HasIndex("ImprovedBlobPathId");

                    b.HasIndex("ImprovementLockedById");

                    b.HasIndex("OriginalBlobPathId");

                    b.HasIndex("RejectedReasonId");

                    b.HasIndex("SponsorId");

                    b.HasIndex("StudentId");

                    b.HasIndex("UploadedById");

                    b.HasIndex("Status", "UploadedOn");

                    b.ToTable("Documents", t =>
                        {
                            t.HasCheckConstraint("CK_Document_ApprovedOrRejected", "[ApprovedOn] IS NULL OR [RejectedOn] IS NULL");

                            t.HasCheckConstraint("CK_Document_ImprovementComplete", "[DigitalImprovementStatus] <> 3 OR [ImprovedBlobPathId] IS NOT NULL");

                            t.HasCheckConstraint("CK_Document_ImprovementNotApplicable", "[DigitalImprovementStatus] <> 0 OR [ImprovedBlobPathId] IS NULL");
                        });

                    b.HasDiscriminator<byte>("DocumentType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Fonbec.Web.DataAccess.Entities.DocumentQueueItem", b =>
                {
                    b.Property<long>("QueueItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("QueueItemId"));

                    b.Property<int>("DequeueCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<long>("DocumentId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("EnqueuedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("ReviewLockedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ReviewLockedById")
                        .HasColumnType("int");

                    b.HasKey("QueueItemId");

                    b.HasIndex("DocumentId")
                        .IsUnique();

                    b.HasIndex("ReviewLockedById");

                    b.ToTable("DocumentQueueItems");
                });

            modelBuilder.Entity("Fonbec.Web.DataAccess.Entities.DocumentShare", b =>
                {
                    b.Property<long>("DocumentShareId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("DocumentShareId"));

                    b.Property<long>("DocumentId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("NotificationSentOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("SharedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("SharedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("SponsorId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("DocumentShareId");

                    b.HasIndex("SharedById");

                    b.HasIndex("SponsorId");

                    b.HasIndex("StudentId");

                    b.HasIndex("DocumentId", "SponsorId")
                        .IsUnique();

                    b.ToTable("DocumentShares");
                });

            modelBuilder.Entity("Fonbec.Web.DataAccess.Entities.FonbecWebRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Fonbec.Web.DataAccess.Entities.FonbecWebUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int?>("ChapterId")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOnUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("DisabledById")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DisabledOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<byte>("Gender")
                        .HasColumnType("tinyint");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int?>("LastUpdatedById")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastUpdatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NickName")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Notes")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<int?>("ReenabledById")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReenabledOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("ChapterId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("DisabledById");

                    b.HasIndex("LastUpdatedById");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("ReenabledById");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Fonbec.Web.DataAccess.Entities.LetterReview", b =>
                {
                    b.Property<long>("LetterReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("LetterReviewId"));

                    b.Property<long>("AssessmentId")
                        .HasColumnType("bigint");

                    b.Property<bool>("ConfirmedAddressee")
                        .HasColumnType("bit");

                    b.Property<bool>("ConfirmedIsLetter")
                        .HasColumnType("bit");

                    b.Property<bool>("ConfirmedSignerMatchesStudent")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ConfirmedWrittenDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("DocumentId")
                        .HasColumnType("bigint");

                    b.Property<int>("ReviewedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReviewedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("LetterReviewId");

                    b.HasIndex("AssessmentId")
                        .IsUnique();

                    b.HasIndex("DocumentId")
                        .IsUnique();

                    b.HasIndex("ReviewedById");

                    b.ToTable("LetterReviews");
                });

            modelBuilder.Entity("Fonbec.Web.DataAccess.Entities.PlannedDelivery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ChapterId")
                        .HasColumnType("int");

                    b.Property<bool>("Completed")
                        .HasColumnType("bit");

                    b.Property<int>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DisabledById")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DisabledOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("LastUpdatedById")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastUpdatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ReenabledById")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReenabledOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartsOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ChapterId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("DisabledById");

                    b.HasIndex("LastUpdatedById");

                    b.HasIndex("ReenabledById");

                    b.ToTable("PlannedDeliveries");
                });

            modelBuilder.Entity("Fonbec.Web.DataAccess.Entities.PointOfContact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DisabledById")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DisabledOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int?>("LastUpdatedById")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastUpdatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("NickName")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Notes")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("ReenabledById")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReenabledOnUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("DisabledById");

                    b.HasIndex("LastUpdatedById");

                    b.HasIndex("ReenabledById");

                    b.ToTable("PointsOfContact");
                });

            modelBuilder.Entity("Fonbec.Web.DataAccess.Entities.RejectedReason", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte?>("AppliesToDocumentType")
                        .HasColumnType("tinyint");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("RequiresNotes")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("RejectedReasons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppliesToDocumentType = (byte)1,
                            Code = "NotALetter",
                            Description = "No es una carta",
                            RequiresNotes = false
                        },
                        new
                        {
                            Id = 2,
                            AppliesToDocumentType = (byte)1,
                            Code = "WrongAddressee",
                            Description = "Destinatario incorrecto",
                            RequiresNotes = false
                        },
                        new
                        {
                            Id = 3,
                            AppliesToDocumentType = (byte)1,
                            Code = "WrongSigner",
                            Description = "Firma incorrecta",
                            RequiresNotes = false
                        },
                        new
                        {
                            Id = 4,
                            AppliesToDocumentType = (byte)1,
                            Code = "Illegible",
                            Description = "Ilegible",
                            RequiresNotes = false
                        },
                        new
                        {
                            Id = 5,
                            AppliesToDocumentType = (byte)1,
                            Code = "InappropriateContent",
                            Description = "Contenido inapropiado",
                            RequiresNotes = false
                        },
                        new
                        {
                            Id = 6,
                            AppliesToDocumentType = (byte)1,
                            Code = "WrongDate",
                            Description = "Fecha incorrecta",
                            RequiresNotes = false
                        },
                        new
                        {
                            Id = 7,
                            AppliesToDocumentType = (byte)2,
                            Code = "NotReportCard",
                            Description = "No es boletín o libreta",
                            RequiresNotes = false
                        },
                        new
                        {
                            Id = 8,
                            AppliesToDocumentType = (byte)2,
                            Code = "WrongStudentName",
                            Description = "Nombre del estudiante incorrecto",
                            RequiresNotes = false
                        },
                        new
                        {
                            Id = 9,
                            AppliesToDocumentType = (byte)3,
                            Code = "Unreadable",
                            Description = "No legible",
                            RequiresNotes = false
                        },
                        new
                        {
                            Id = 10,
                            AppliesToDocumentType = (byte)3,
                            Code = "WrongDocument",
                            Description = "Documento incorrecto",
                            RequiresNotes = false
                        },
                        new
                        {
                            Id = 11,
                            Code = "Other",
                            Description = "Otro",
                            RequiresNotes = true
                        });
                });

            modelBuilder.Entity("Fonbec.Web.DataAccess.Entities.ReportCardReview", b =>
                {
                    b.Property<long>("ReportCardReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ReportCardReviewId"));

                    b.Property<bool>("ConfirmedIsReportCardOrTranscript")
                        .HasColumnType("bit");

                    b.Property<bool>("ConfirmedStudentNameCorrect")
                        .HasColumnType("bit");

                    b.Property<long>("DocumentId")
                        .HasColumnType("bigint");

                    b.Property<int>("ReviewedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReviewedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("ReportCardReviewId");

                    b.HasIndex("DocumentId")
                        .IsUnique();

                    b.HasIndex("ReviewedById");

                    b.ToTable("ReportCardReviews");
                });

            modelBuilder.Entity("Fonbec.Web.DataAccess.Entities.Sponsor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChapterId")
                        .HasColumnType("int");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DisabledById")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DisabledOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<byte>("Gender")
                        .HasColumnType("tinyint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int?>("LastUpdatedById")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastUpdatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("NickName")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Notes")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<byte>("NotificationPreference")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)0);

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("PublicAccessToken")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("ReenabledById")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReenabledOnUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ChapterId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("DisabledById");

                    b.HasIndex("LastUpdatedById");

                    b.HasIndex("PublicAccessToken")
                        .IsUnique();

                    b.HasIndex("ReenabledById");

                    b.ToTable("Sponsors");
                });

            modelBuilder.Entity("Fonbec.Web.DataAccess.Entities.Sponsorship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DisabledById")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DisabledOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("LastUpdatedById")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastUpdatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int?>("ReenabledById")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReenabledOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SponsorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("DisabledById");

                    b.HasIndex("LastUpdatedById");

                    b.HasIndex("ReenabledById");

                    b.HasIndex("SponsorId");

                    b.HasIndex("StudentId");

                    b.ToTable("Sponsorships");
                });

            modelBuilder.Entity("Fonbec.Web.DataAccess.Entities.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChapterId")
                        .HasColumnType("int");

                    b.Property<int>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DisabledById")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DisabledOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("FacilitatorId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<byte>("Gender")
                        .HasColumnType("tinyint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int?>("LastUpdatedById")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastUpdatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("NickName")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Notes")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("ReenabledById")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReenabledOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SecondarySchoolStartYear")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UniversityStartYear")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ChapterId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("DisabledById");

                    b.HasIndex("FacilitatorId");

                    b.HasIndex("LastUpdatedById");

                    b.HasIndex("ReenabledById");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Fonbec.Web.DataAccess.Entities.Letter", b =>
                {
                    b.HasBaseType("Fonbec.Web.DataAccess.Entities.Document");

                    b.Property<int>("PlanId")
                        .HasColumnType("int");

                    b.HasIndex("PlanId");

                    b.HasIndex("StudentId", "SponsorId", "PlanId")
                        .IsUnique()
                        .HasFilter("[DocumentType] = 1 AND [Status] <> 5");

                    b.ToTable("Documents", t =>
                        {
                            t.HasCheckConstraint("CK_Document_ApprovedOrRejected", "[ApprovedOn] IS NULL OR [RejectedOn] IS NULL");

                            t.HasCheckConstraint("CK_Document_ImprovementComplete", "[DigitalImprovementStatus] <> 3 OR [ImprovedBlobPathId] IS NOT NULL");

                            t.HasCheckConstraint("CK_Document_ImprovementNotApplicable", "[DigitalImprovementStatus] <> 0 OR [ImprovedBlobPathId] IS NULL");

                            t.HasCheckConstraint("CK_Letter_SponsorRequired", "[DocumentType] <> 1 OR [SponsorId] IS NOT NULL");
                        });

                    b.HasDiscriminator().HasValue((byte)1);
                });

            modelBuilder.Entity("Fonbec.Web.DataAccess.Entities.OtherDocument", b =>
                {
                    b.HasBaseType("Fonbec.Web.DataAccess.Entities.Document");

                    b.ToTable("Documents", t =>
                        {
                            t.HasCheckConstraint("CK_Document_ApprovedOrRejected", "[ApprovedOn] IS NULL OR [RejectedOn] IS NULL");

                            t.HasCheckConstraint("CK_Document_ImprovementComplete", "[DigitalImprovementStatus] <> 3 OR [ImprovedBlobPathId] IS NOT NULL");

                            t.HasCheckConstraint("CK_Document_ImprovementNotApplicable", "[DigitalImprovementStatus] <> 0 OR [ImprovedBlobPathId] IS NULL");

                            t.HasCheckConstraint("CK_OtherDocument_SponsorNull", "[DocumentType] <> 3 OR [SponsorId] IS NULL");
                        });

                    b.HasDiscriminator().HasValue((byte)3);
                });

            modelBuilder.Entity("Fonbec.Web.DataAccess.Entities.ReportCard", b =>
                {
                    b.HasBaseType("Fonbec.Web.DataAccess.Entities.Document");

                    b.ToTable("Documents", t =>
                        {
                            t.HasCheckConstraint("CK_Document_ApprovedOrRejected", "[ApprovedOn] IS NULL OR [RejectedOn] IS NULL");

                            t.HasCheckConstraint("CK_Document_ImprovementComplete", "[DigitalImprovementStatus] <> 3 OR [ImprovedBlobPathId] IS NOT NULL");

                            t.HasCheckConstraint("CK_Document_ImprovementNotApplicable", "[DigitalImprovementStatus] <> 0 OR [ImprovedBlobPathId] IS NULL");

                            t.HasCheckConstraint("CK_ReportCard_SponsorNull", "[DocumentType] <> 2 OR [SponsorId] IS NULL");
                        });

                    b.HasDiscriminator().HasValue((byte)2);
                });

            modelBuilder.Entity("Fonbec.Web.DataAccess.Entities.Chapter", b =>
                {
                    b.HasOne("Fonbec.Web.DataAccess.Entities.FonbecWebUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fonbec.Web.DataAccess.Entities.FonbecWebUser", "DisabledBy")
                        .WithMany()
                        .HasForeignKey("DisabledById");

                    b.HasOne("Fonbec.Web.DataAccess.Entities.FonbecWebUser", "LastUpdatedBy")
                        .WithMany()
                        .HasForeignKey("LastUpdatedById");

                    b.HasOne("Fonbec.Web.DataAccess.Entities.FonbecWebUser", "ReenabledBy")
                        .WithMany()
                        .HasForeignKey("ReenabledById");

                    b.Navigation("CreatedBy");

                    b.Navigation("DisabledBy");

                    b.Navigation("LastUpdatedBy");

                    b.Navigation("ReenabledBy");
                });

            modelBuilder.Entity("Fonbec.Web.DataAccess.Entities.Company", b =>
                {
                    b.HasOne("Fonbec.Web.DataAccess.Entities.FonbecWebUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fonbec.Web.DataAccess.Entities.FonbecWebUser", "DisabledBy")
                        .WithMany()
                        .HasForeignKey("DisabledById");

                    b.HasOne("Fonbec.Web.DataAccess.Entities.FonbecWebUser", "LastUpdatedBy")
                        .WithMany()
                        .HasForeignKey("LastUpdatedById");

                    b.HasOne("Fonbec.Web.DataAccess.Entities.FonbecWebUser", "ReenabledBy")
                        .WithMany()
                        .HasForeignKey("ReenabledById");

                    b.Navigation("CreatedBy");

                    b.Navigation("DisabledBy");

                    b.Navigation("LastUpdatedBy");

                    b.Navigation("ReenabledBy");
                });

            modelBuilder.Entity("Fonbec.Web.DataAccess.Entities.Document", b =>
                {
                    b.HasOne("Fonbec.Web.DataAccess.Entities.BlobPath", "BlobPath")
                        .WithMany()
                        .HasForeignKey("BlobPathId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Fonbec.Web.DataAccess.Entities.Chapter", "Chapter")
                        .WithMany()
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Fonbec.Web.DataAccess.Entities.BlobPath", "ImprovedBlobPath")
                        .WithMany()
                        .HasForeignKey("ImprovedBlobPathId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Fonbec.Web.DataAccess.Entities.FonbecWebUser", "ImprovementLockedBy")
                        .WithMany()
                        .HasForeignKey("ImprovementLockedById")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Fonbec.Web.DataAccess.Entities.BlobPath", "OriginalBlobPath")
                        .WithMany()
                        .HasForeignKey("OriginalBlobPathId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Fonbec.Web.DataAccess.Entities.RejectedReason", "RejectedReason")
                        .WithMany()
                        .HasForeignKey("RejectedReasonId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Fonbec.Web.DataAccess.Entities.Sponsor", "Sponsor")
                        .WithMany()
                        .HasForeignKey("SponsorId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Fonbec.Web.DataAccess.Entities.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Fonbec.Web.DataAccess.Entities.FonbecWebUser", "UploadedBy")
                        .WithMany()
                        .HasForeignKey("UploadedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("BlobPath");

                    b.Navigation("Chapter");

                    b.Navigation("ImprovedBlobPath");

                    b.Navigation("ImprovementLockedBy");

                    b.Navigation("OriginalBlobPath");

                    b.Navigation("RejectedReason");

                    b.Navigation("Sponsor");

                    b.Navigation("Student");

                    b.Navigation("UploadedBy");
                });

            modelBuilder.Entity("Fonbec.Web.DataAccess.Entities.DocumentQueueItem", b =>
                {
                    b.HasOne("Fonbec.Web.DataAccess.Entities.Document", "Document")
                        .WithOne("QueueItem")
                        .HasForeignKey("Fonbec.Web.DataAccess.Entities.DocumentQueueItem", "DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fonbec.Web.DataAccess.Entities.FonbecWebUser", "ReviewLockedBy")
                        .WithMany()
                        .HasForeignKey("ReviewLockedById")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Document");

                    b.Navigation("ReviewLockedBy");
                });

            modelBuilder.Entity("Fonbec.Web.DataAccess.Entities.DocumentShare", b =>
                {
                    b.HasOne("Fonbec.Web.DataAccess.Entities.Document", "Document")
                        .WithMany("Shares")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fonbec.Web.DataAccess.Entities.FonbecWebUser", "SharedBy")
                        .WithMany()
                        .HasForeignKey("SharedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Fonbec.Web.DataAccess.Entities.Sponsor", "Sponsor")
                        .WithMany()
                        .HasForeignKey("SponsorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Fonbec.Web.DataAccess.Entities.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Document");

                    b.Navigation("SharedBy");

                    b.Navigation("Sponsor");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Fonbec.Web.DataAccess.Entities.FonbecWebUser", b =>
                {
                    b.HasOne("Fonbec.Web.DataAccess.Entities.Chapter", "Chapter")
                        .WithMany()
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Fonbec.Web.DataAccess.Entities.FonbecWebUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Fonbec.Web.DataAccess.Entities.FonbecWebUser", "DisabledBy")
                        .WithMany()
                        .HasForeignKey("DisabledById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Fonbec.Web.DataAccess.Entities.FonbecWebUser", "LastUpdatedBy")
                        .WithMany()
                        .HasForeignKey("LastUpdatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Fonbec.Web.DataAccess.Entities.FonbecWebUser", "ReenabledBy")
                        .WithMany()
                        .HasForeignKey("ReenabledById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Chapter");

                    b.Navigation("CreatedBy");

                    b.Navigation("DisabledBy");

                    b.Navigation("LastUpdatedBy");

                    b.Navigation("ReenabledBy");
                });

            modelBuilder.Entity("Fonbec.Web.DataAccess.Entities.LetterReview", b =>
                {
                    b.HasOne("Fonbec.Web.DataAccess.Entities.Assessment", "Assessment")
                        .WithOne("LetterReview")
                        .HasForeignKey("Fonbec.Web.DataAccess.Entities.LetterReview", "AssessmentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Fonbec.Web.DataAccess.Entities.Letter", "Document")
                        .WithOne("Review")
                        .HasForeignKey("Fonbec.Web.DataAccess.Entities.LetterReview", "DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fonbec.Web.DataAccess.Entities.FonbecWebUser", "ReviewedBy")
                        .WithMany()
                        .HasForeignKey("ReviewedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Assessment");

                    b.Navigation("Document");

                    b.Navigation("ReviewedBy");
                });

            modelBuilder.Entity("Fonbec.Web.DataAccess.Entities.PlannedDelivery", b =>
                {
                    b.HasOne("Fonbec.Web.DataAccess.Entities.Chapter", "Chapter")
                        .WithMany()
                        .HasForeignKey("ChapterId");

                    b.HasOne("Fonbec.Web.DataAccess.Entities.FonbecWebUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fonbec.Web.DataAccess.Entities.FonbecWebUser", "DisabledBy")
                        .WithMany()
                        .HasForeignKey("DisabledById");

                    b.HasOne("Fonbec.Web.DataAccess.Entities.FonbecWebUser", "LastUpdatedBy")
                        .WithMany()
                        .HasForeignKey("LastUpdatedById");

                    b.HasOne("Fonbec.Web.DataAccess.Entities.FonbecWebUser", "ReenabledBy")
                        .WithMany()
                        .HasForeignKey("ReenabledById");

                    b.Navigation("Chapter");

                    b.Navigation("CreatedBy");

                    b.Navigation("DisabledBy");

                    b.Navigation("LastUpdatedBy");

                    b.Navigation("ReenabledBy");
                });

            modelBuilder.Entity("Fonbec.Web.DataAccess.Entities.PointOfContact", b =>
                {
                    b.HasOne("Fonbec.Web.DataAccess.Entities.Company", "Company")
                        .WithMany("PointsOfContact")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Fonbec.Web.DataAccess.Entities.FonbecWebUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fonbec.Web.DataAccess.Entities.FonbecWebUser", "DisabledBy")
                        .WithMany()
                        .HasForeignKey("DisabledById");

                    b.HasOne("Fonbec.Web.DataAccess.Entities.FonbecWebUser", "LastUpdatedBy")
                        .WithMany()
                        .HasForeignKey("LastUpdatedById");

                    b.HasOne("Fonbec.Web.DataAccess.Entities.FonbecWebUser", "ReenabledBy")
                        .WithMany()
                        .HasForeignKey("ReenabledById");

                    b.Navigation("Company");

                    b.Navigation("CreatedBy");

                    b.Navigation("DisabledBy");

                    b.Navigation("LastUpdatedBy");

                    b.Navigation("ReenabledBy");
                });

            modelBuilder.Entity("Fonbec.Web.DataAccess.Entities.ReportCardReview", b =>
                {
                    b.HasOne("Fonbec.Web.DataAccess.Entities.ReportCard", "Document")
                        .WithOne("Review")
                        .HasForeignKey("Fonbec.Web.DataAccess.Entities.ReportCardReview", "DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fonbec.Web.DataAccess.Entities.FonbecWebUser", "ReviewedBy")
                        .WithMany()
                        .HasForeignKey("ReviewedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Document");

                    b.Navigation("ReviewedBy");
                });

            modelBuilder.Entity("Fonbec.Web.DataAccess.Entities.Sponsor", b =>
                {
                    b.HasOne("Fonbec.Web.DataAccess.Entities.Chapter", "Chapter")
                        .WithMany()
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Fonbec.Web.DataAccess.Entities.Company", "Company")
                        .WithMany("Sponsors")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Fonbec.Web.DataAccess.Entities.FonbecWebUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fonbec.Web.DataAccess.Entities.FonbecWebUser", "DisabledBy")
                        .WithMany()
                        .HasForeignKey("DisabledById");

                    b.HasOne("Fonbec.Web.DataAccess.Entities.FonbecWebUser", "LastUpdatedBy")
                        .WithMany()
                        .HasForeignKey("LastUpdatedById");

                    b.HasOne("Fonbec.Web.DataAccess.Entities.FonbecWebUser", "ReenabledBy")
                        .WithMany()
                        .HasForeignKey("ReenabledById");

                    b.Navigation("Chapter");

                    b.Navigation("Company");

                    b.Navigation("CreatedBy");

                    b.Navigation("DisabledBy");

                    b.Navigation("LastUpdatedBy");

                    b.Navigation("ReenabledBy");
                });

            modelBuilder.Entity("Fonbec.Web.DataAccess.Entities.Sponsorship", b =>
                {
                    b.HasOne("Fonbec.Web.DataAccess.Entities.Company", "Company")
                        .WithMany("Sponsorships")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Fonbec.Web.DataAccess.Entities.FonbecWebUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fonbec.Web.DataAccess.Entities.FonbecWebUser", "DisabledBy")
                        .WithMany()
                        .HasForeignKey("DisabledById");

                    b.HasOne("Fonbec.Web.DataAccess.Entities.FonbecWebUser", "LastUpdatedBy")
                        .WithMany()
                        .HasForeignKey("LastUpdatedById");

                    b.HasOne("Fonbec.Web.DataAccess.Entities.FonbecWebUser", "ReenabledBy")
                        .WithMany()
                        .HasForeignKey("ReenabledById");

                    b.HasOne("Fonbec.Web.DataAccess.Entities.Sponsor", "Sponsor")
                        .WithMany("Sponsorships")
                        .HasForeignKey("SponsorId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Fonbec.Web.DataAccess.Entities.Student", "Student")
                        .WithMany("Sponsorships")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("CreatedBy");

                    b.Navigation("DisabledBy");

                    b.Navigation("LastUpdatedBy");

                    b.Navigation("ReenabledBy");

                    b.Navigation("Sponsor");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Fonbec.Web.DataAccess.Entities.Student", b =>
                {
                    b.HasOne("Fonbec.Web.DataAccess.Entities.Chapter", "Chapter")
                        .WithMany()
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Fonbec.Web.DataAccess.Entities.FonbecWebUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fonbec.Web.DataAccess.Entities.FonbecWebUser", "DisabledBy")
                        .WithMany()
                        .HasForeignKey("DisabledById");

                    b.HasOne("Fonbec.Web.DataAccess.Entities.FonbecWebUser", "Facilitator")
                        .WithMany("Students")
                        .HasForeignKey("FacilitatorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Fonbec.Web.DataAccess.Entities.FonbecWebUser", "LastUpdatedBy")
                        .WithMany()
                        .HasForeignKey("LastUpdatedById");

                    b.HasOne("Fonbec.Web.DataAccess.Entities.FonbecWebUser", "ReenabledBy")
                        .WithMany()
                        .HasForeignKey("ReenabledById");

                    b.Navigation("Chapter");

                    b.Navigation("CreatedBy");

                    b.Navigation("DisabledBy");

                    b.Navigation("Facilitator");

                    b.Navigation("LastUpdatedBy");

                    b.Navigation("ReenabledBy");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Fonbec.Web.DataAccess.Entities.FonbecWebRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("Fonbec.Web.DataAccess.Entities.FonbecWebUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("Fonbec.Web.DataAccess.Entities.FonbecWebUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Fonbec.Web.DataAccess.Entities.FonbecWebRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fonbec.Web.DataAccess.Entities.FonbecWebUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("Fonbec.Web.DataAccess.Entities.FonbecWebUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fonbec.Web.DataAccess.Entities.Letter", b =>
                {
                    b.HasOne("Fonbec.Web.DataAccess.Entities.PlannedDelivery", "Plan")
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("Fonbec.Web.DataAccess.Entities.Assessment", b =>
                {
                    b.Navigation("LetterReview");
                });

            modelBuilder.Entity("Fonbec.Web.DataAccess.Entities.Company", b =>
                {
                    b.Navigation("PointsOfContact");

                    b.Navigation("Sponsors");

                    b.Navigation("Sponsorships");
                });

            modelBuilder.Entity("Fonbec.Web.DataAccess.Entities.Document", b =>
                {
                    b.Navigation("QueueItem");

                    b.Navigation("Shares");
                });

            modelBuilder.Entity("Fonbec.Web.DataAccess.Entities.FonbecWebUser", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("Fonbec.Web.DataAccess.Entities.Sponsor", b =>
                {
                    b.Navigation("Sponsorships");
                });

            modelBuilder.Entity("Fonbec.Web.DataAccess.Entities.Student", b =>
                {
                    b.Navigation("Sponsorships");
                });

            modelBuilder.Entity("Fonbec.Web.DataAccess.Entities.Letter", b =>
                {
                    b.Navigation("Review");
                });

            modelBuilder.Entity("Fonbec.Web.DataAccess.Entities.ReportCard", b =>
                {
                    b.Navigation("Review");
                });
#pragma warning restore 612, 618
        }
    }
}
