name: Branch Name Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch name
        run: |
          echo "Validating branch name: ${{ github.head_ref }}"
          if [[ ! "${{ github.head_ref }}" =~ ^feature/[0-9]+-[A-Z][a-zA-Z0-9_\-]+$ ]]; then
            echo "::error::Branch name must follow the pattern 'feature/N-Description' (e.g., feature/123-Add-Login)"
            exit 1
          fi
